const express = require('express');
const multer = require('multer');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

const app = express();
const PORT = process.env.PORT || 3099;

const CERT_DIR = process.env.CERT_DIR || '/etc/nginx/ssl';
const SITES_AVAILABLE = process.env.SITES_AVAILABLE || '/etc/nginx/sites-available';
const SITES_ENABLED = process.env.SITES_ENABLED || '/etc/nginx/sites-enabled';
const CONFIG_FILE = path.join(__dirname, 'config.json');

app.use(cors());
app.use(express.json());

if (process.env.NODE_ENV === 'production') {
  app.use(express.static(path.join(__dirname, '..', 'frontend', 'dist')));
}

// --- Multer for cert upload ---
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    if (!fs.existsSync(CERT_DIR)) fs.mkdirSync(CERT_DIR, { recursive: true });
    cb(null, CERT_DIR);
  },
  filename: (req, file, cb) => {
    const config = loadConfig();
    const domain = config.domain || 'default';
    cb(null, file.fieldname === 'fullchain' ? `${domain}.crt` : `${domain}.key`);
  }
});
const upload = multer({
  storage,
  fileFilter: (req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    if (['.pem', '.crt', '.key', '.cer'].includes(ext) || file.mimetype === 'application/octet-stream') {
      cb(null, true);
    } else {
      cb(new Error(`不支持的文件类型: ${ext}`));
    }
  },
  limits: { fileSize: 1024 * 1024 }
});

// --- Config ---
// { domain: "example.com", sites: [{ name: "web", path: "/", port: "3000" }] }
function loadConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf-8'));
  } catch (e) { /* ignore */ }
  return { domain: '', sites: [] };
}
function saveConfig(config) {
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2), 'utf-8');
}

// --- Nginx helpers ---
function checkNginx() {
  const result = { installed: false, version: null, running: false, path: null };
  try {
    const out = execSync('nginx -v 2>&1', { encoding: 'utf-8' });
    result.installed = true;
    const m = out.match(/nginx\/(\S+)/);
    result.version = m ? m[1] : out.trim();
  } catch (e) { return result; }
  try { result.path = execSync('which nginx 2>/dev/null', { encoding: 'utf-8' }).trim(); } catch (e) {}
  try { execSync('pgrep -x nginx >/dev/null 2>&1'); result.running = true; } catch (e) {}
  return result;
}

function detectPM() {
  const list = [
    { cmd: 'apt-get --version', name: 'apt', install: 'apt-get update && apt-get install -y nginx' },
    { cmd: 'yum --version', name: 'yum', install: 'yum install -y nginx' },
    { cmd: 'dnf --version', name: 'dnf', install: 'dnf install -y nginx' },
    { cmd: 'pacman --version', name: 'pacman', install: 'pacman -S --noconfirm nginx' },
    { cmd: 'brew --version', name: 'brew', install: 'brew install nginx' },
    { cmd: 'apk --version', name: 'apk', install: 'apk add --no-cache nginx' },
  ];
  for (const p of list) {
    try { execSync(p.cmd + ' >/dev/null 2>&1'); return p; } catch (e) {}
  }
  return null;
}

// Generate ONE nginx config with all location blocks
function generateNginxConfig(domain, sites) {
  const locations = sites.map(s => {
    const loc = s.path === '/' ? '/' : s.path;
    return `    # ${s.name}
    location ${loc} {
        proxy_pass http://127.0.0.1:${s.port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }`;
  }).join('\n\n');

  return `# Auto-generated by Auto Nginx — ${new Date().toISOString()}
server {
    listen 80;
    server_name ${domain};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${domain};

    ssl_certificate     ${CERT_DIR}/${domain}.crt;
    ssl_certificate_key ${CERT_DIR}/${domain}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

${locations}

    access_log /var/log/nginx/${domain}_access.log;
    error_log  /var/log/nginx/${domain}_error.log;
}
`;
}

function getCertStatus(domain) {
  if (!domain) return false;
  return fs.existsSync(path.join(CERT_DIR, `${domain}.crt`)) &&
         fs.existsSync(path.join(CERT_DIR, `${domain}.key`));
}

function getDeployStatus(domain) {
  if (!domain) return { configExists: false, enabled: false };
  return {
    configExists: fs.existsSync(path.join(SITES_AVAILABLE, domain)),
    enabled: fs.existsSync(path.join(SITES_ENABLED, domain)),
  };
}

// Deploy (regenerate full config)
function deployAll() {
  const config = loadConfig();
  if (!config.domain) throw new Error('请先设置域名');
  if (!getCertStatus(config.domain)) throw new Error('请先上传 SSL 证书');
  if (config.sites.length === 0) throw new Error('请至少添加一个站点');

  if (!fs.existsSync(SITES_AVAILABLE)) fs.mkdirSync(SITES_AVAILABLE, { recursive: true });
  if (!fs.existsSync(SITES_ENABLED)) fs.mkdirSync(SITES_ENABLED, { recursive: true });

  const availablePath = path.join(SITES_AVAILABLE, config.domain);
  const enabledPath = path.join(SITES_ENABLED, config.domain);

  fs.writeFileSync(availablePath, generateNginxConfig(config.domain, config.sites), 'utf-8');
  if (fs.existsSync(enabledPath)) fs.unlinkSync(enabledPath);
  fs.symlinkSync(availablePath, enabledPath);

  try {
    execSync('nginx -t 2>&1', { encoding: 'utf-8' });
  } catch (e) {
    if (fs.existsSync(enabledPath)) fs.unlinkSync(enabledPath);
    if (fs.existsSync(availablePath)) fs.unlinkSync(availablePath);
    throw new Error('Nginx 配置测试失败，已回滚: ' + (e.stderr || e.message));
  }
  execSync('nginx -s reload 2>&1', { encoding: 'utf-8' });
}

// ==================== API ====================

// Nginx check & install
app.get('/api/nginx-check', (req, res) => {
  const info = checkNginx();
  const pm = detectPM();
  res.json({ ...info, packageManager: pm?.name || null, canAutoInstall: !!pm });
});

app.post('/api/nginx-install', (req, res) => {
  const cur = checkNginx();
  if (cur.installed) return res.json({ success: true, message: `Nginx 已安装 (v${cur.version})`, ...cur });
  const pm = detectPM();
  if (!pm) return res.status(400).json({ error: '无法检测到包管理器，请手动安装 Nginx' });
  try {
    execSync(pm.install + ' 2>&1', { encoding: 'utf-8', timeout: 120000 });
    const after = checkNginx();
    if (!after.installed) return res.status(500).json({ error: '安装命令执行但未成功' });
    try { execSync('nginx 2>&1 || systemctl start nginx 2>&1 || service nginx start 2>&1'); after.running = true; } catch (e) {}
    res.json({ success: true, message: `Nginx v${after.version} 安装成功`, ...after });
  } catch (err) {
    res.status(500).json({ error: `安装失败 (${pm.name})`, detail: err.stdout || err.stderr || err.message });
  }
});

// Global status (domain, cert, deploy, sites)
app.get('/api/status', (req, res) => {
  const config = loadConfig();
  const deploy = getDeployStatus(config.domain);
  res.json({
    domain: config.domain || '',
    certReady: getCertStatus(config.domain),
    sites: config.sites,
    ...deploy,
  });
});

// Set domain
app.post('/api/domain', (req, res) => {
  const { domain } = req.body;
  if (!domain?.trim()) return res.status(400).json({ error: '请输入域名' });
  const config = loadConfig();
  config.domain = domain.trim();
  saveConfig(config);
  res.json({ success: true, message: `域名已设置为 ${config.domain}` });
});

// Upload certificate (global, for the configured domain)
app.post('/api/certificate', upload.fields([
  { name: 'fullchain', maxCount: 1 },
  { name: 'privkey', maxCount: 1 }
]), (req, res) => {
  const config = loadConfig();
  if (!config.domain) return res.status(400).json({ error: '请先设置域名' });
  if (!req.files?.fullchain || !req.files?.privkey) {
    return res.status(400).json({ error: '请同时上传证书文件和私钥文件' });
  }
  res.json({ success: true, message: '证书上传成功', certReady: true });
});

// Add site (just name/path + port)
app.post('/api/sites', (req, res) => {
  const { name, path: sitePath, port } = req.body;
  if (!name?.trim() || !port) return res.status(400).json({ error: '请填写名称和端口' });
  const portNum = parseInt(port, 10);
  if (isNaN(portNum) || portNum < 1 || portNum > 65535) return res.status(400).json({ error: '端口号 1-65535' });

  const config = loadConfig();
  const finalPath = (sitePath?.trim() || '/').replace(/\/$/, '') || '/';
  if (config.sites.find(s => s.name === name.trim())) {
    return res.status(400).json({ error: `站点名称 "${name}" 已存在` });
  }

  config.sites.push({
    name: name.trim(),
    path: finalPath,
    port: String(portNum),
    createdAt: new Date().toISOString()
  });
  saveConfig(config);
  res.json({ success: true, message: `站点 "${name}" 已添加` });
});

// Delete site
app.delete('/api/sites/:name', (req, res) => {
  const name = decodeURIComponent(req.params.name);
  const config = loadConfig();
  config.sites = config.sites.filter(s => s.name !== name);
  saveConfig(config);
  res.json({ success: true, message: `站点 "${name}" 已删除` });
});

// Deploy all sites
app.post('/api/deploy', (req, res) => {
  try {
    deployAll();
    res.json({ success: true, message: '部署成功！Nginx 已重载' });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// Undeploy (remove config)
app.post('/api/undeploy', (req, res) => {
  const config = loadConfig();
  if (!config.domain) return res.status(400).json({ error: '没有配置' });
  const enabledPath = path.join(SITES_ENABLED, config.domain);
  const availablePath = path.join(SITES_AVAILABLE, config.domain);
  try { if (fs.existsSync(enabledPath)) fs.unlinkSync(enabledPath); } catch (e) {}
  try { if (fs.existsSync(availablePath)) fs.unlinkSync(availablePath); } catch (e) {}
  try { execSync('nginx -s reload 2>&1'); } catch (e) {}
  res.json({ success: true, message: '已移除部署' });
});

// Preview config
app.get('/api/preview', (req, res) => {
  const config = loadConfig();
  if (!config.domain || config.sites.length === 0) {
    return res.status(400).json({ error: '请先设置域名和添加站点' });
  }
  res.json({ config: generateNginxConfig(config.domain, config.sites) });
});

// Production fallback
if (process.env.NODE_ENV === 'production') {
  app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, '..', 'frontend', 'dist', 'index.html'));
  });
}

app.use((err, req, res, next) => {
  if (err instanceof multer.MulterError) return res.status(400).json({ error: `上传错误: ${err.message}` });
  if (err) return res.status(500).json({ error: err.message });
  next();
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`\n  Auto Nginx Server · http://0.0.0.0:${PORT}\n`);
});
